### ISSUE TITLE
OAuth Token Now Required To Search Spotify

### ISSUE THREAD

**Issue by lpaniccia** [xzzz9097/Swiftify#2]
Spotify updated their API and is now requiring an OAuth token to use the Search endpoint:
https://developer.spotify.com/web-api/console/get-search-item/

swiftify.find will need to be updated to include the user's token in the GET request.

**Comment by xzzz9097** [comment]
Thanks, I've updated it to make it work again with bf08e620c086d1672f7052b83f625c04e27efd8f commit. Although I don't really understand why Spotify now requires token even for basic, account-unrelated searches.
